title: Ali BaObaid
subtitle: ROR developer
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Ali BaObaid
author_bio: Hi, I am a back end developer using ruby on rails API, coding with unit test and dealing with integrations and microservice apps
author_email: "ali.baobaid.me@gmail.com"
author_location: Yemen
author_website_url: "https://alibaobaid.me"
typewrite-text: A back end developer using ruby on rails API, coding with unit test and dealing with integrations and microservice apps
author_work_experiences: 
            - company_name: JISR HR
              company_logo: jisr_logo.jpg
              company_url: https://jisr.net
              designation: Back end 
              description: Worked beside amazing group we are coding with fun using ROR and RSpec
              visibility: true
            - company_name: Hadhramaut University, College of Computers
              company_logo: uni.png
              company_url: http://hu.edu.ye/
              designation: Teacher Assistant 
              description: 
              visibility: true

author_education_details:
              - college_logo: al-ahgaff.jpg
                college_name: Al Ahgaff
                college_url: https://ahgaff.edu/
                college_degree: Faculty of Computer Science & Engineering
                description: CIS Department
                visibility: true

author_project_details:
              - project_thumbnail: no_limits.png
                project_title: Web Application For No-Limits Foundation
                project_description: Application to automate the daily tasks of the Foundation 
                project_url:
                visibility: true
              - project_thumbnail: tutor.png
                project_title: Mudaris Web Application
                project_description: A Platform to easily find for Tutor in school Subjects in your place
                project_url:
                visibility: true

# social links
twitter_username: alibaobaid_me
github_username:  alibaobaid
facebook_username: alibaobaid.me
linkedin_username: alibaobaid
medium_username: alibaobaid.me

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 1948

# wakatime username (coding activity)
wakatime_username: ali_baobiad

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: xzbdanla

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# # Gallery
# defaults:
#   -
#     scope:
#       path: "gallery"
#     values:
#       permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
